name: Publish Extension
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Make sure the version number in the tag matches the version in package.json
      - name: match-tag-to-package-version
        uses: geritol/match-tag-to-package-version@0.2.0
        env:
          TAG_PREFIX: v

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Publish to Marketplace
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
